In [0]:
import numpy as np
import random

#Mini training set for a AND gate

#a numpy array containing 4 possible pairs with (in1, in2, out)
training_set = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

In [0]:
training_in = training_set[:, :2]
training_out = training_set[:, 2]

In [0]:
class Neural_Network:
  def __init__(self):
    # Seed the random number generator, so it generates the same numbers
    # every time the program runs.
    #random.seed(1)
    
    #only one neuron, using the sigmoid function to transform (-1, 1)
    self.weights = 2 * np.random.random((3,)) - 1
  def identity(self, x):
    return x
  def identity_der(self, x):
    return np.ones(x.shape)
  def sigmoid_function(self, x):
    return 1/(1 + np.exp(-x))
  def sigmoid_der(self, x):
    return x * (1 - x)
  def activate(self, func, x):
    return func(np.dot(x, self.weights))
  def train(self, train_in, train_out, step_size = .005, iters = 100):
    
    num_data = train_in.shape[0]
    for i in range(iters):
      #find output using current weights
      
      for j in range(num_data):
        data_in = train_in[j] 
        data_out = train_out[j]
        
        data_in.append(1)
        data_out.append(1)
        
        out_curr = self.activate(self.sigmoid_function, data_in)
        #error from real value
        error = out_curr - data_out
        
        #update the weights
        #define S(x) to be 1/2 the average squared error over individual training examples
        dSdz = 1.0/num_data * error
        dzdy = self.sigmoid_der(out_curr)
        dydw = data_in
        
        
        dSdw = dSdz * dzdy * dydw 
        #print(self.weights)
        self.weights -= step_size * dSdw
      if i==0 or i==num_data-1:
        print(dSdw, self.weights)
  

In [144]:
nn = Neural_Network()
nn.sigmoid_function(np.array([0, 0]))

array([0.5, 0.5])

In [145]:
nn = Neural_Network()

#train the network
nn.train(training_in, training_out, .5, 100000)

#test it out
nn.activate(nn.sigmoid_function, [0,0])

(array([-0.09509188, -0.09509188]), array([-0.5184156 ,  1.03079053]))
(array([-0.05633437, -0.05633437]), array([-0.20100722,  1.20353954]))


0.5

In [89]:
import numpy as np

# data points
X = np.array([[1, 2], [3, -3], [-2, 2], [2, 5], [4, -1]])
y_true = np.array([-1.4, 24.2, -16.2, -5.1, 22.9])
n_points = X.shape[0]

# set update rate
alpha = 0.1

# initialize our guess for w
w = np.array([3, -5])

# iterate over the data set 20 times
for iter in range(20):

    # iterate over each data point
    for p in range(n_points):
        x = X[p]
        yn = y_true[p]

        # forward pass
        y = np.dot(w, x)

        # backward pass
        dSdy = 1.0/n_points * (y - yn)
        dydw = x
        dSdw = dSdy * dydw

        # update w
        w = w - alpha * dSdw
print(w)

[ 4.99122455 -3.03531958]
